config/routes.rb
Rails.application.routes.draw do
  resources :movies   
   root "movies#index"
   
   get "home" =>"movies#home",as: :home 
   get "pricing" =>"movies#pricing",as: :pricing
   get "new" =>"movies#new",as: :new
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
   validates :title, :category, :price, :year, presence: true # Make sure the owner's name is present.   

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
   def index   
      @movies = Movie.all   
   end  
   def show
    @movies = Movie.find(params[:id])
  end 
      
   def new   
      @movies = Movie.new   
   end

   def home
    end

   def pricing
        end

        def edit
            @movies = Movie.find(params[:id])
          end 

   def create   
      @movies = Movie.new(movie_params)   
         
      if @movies.save   
         redirect_to movies_path, notice: "Successfully uploaded."   
      else   
         render "new"   
      end   
         
   end  
   def update
    @movies = Movie.find(params[:id])
    redirect_to movies_path, notice: "Successfully updated ."  
    if @movies.update(movie_params)
      
    else
      render 'edit'
    end
  end
      
   def destroy   
      @movies = Movie.find(params[:id])   
      @movies.destroy   
      redirect_to movies_path, notice:  "Successfully deleted."   
   end   
      
   private   
      def movie_params   
      params.require(:movie).permit(:title, :category, :price, :year, :attachment)   
   end   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>   
<html>   
 <head>   
      <title>Jorah Entertenement</title>   
      <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>   
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>   
      <%= csrf_meta_tags %>   
   </head>   
      
   <body>   
      <div>
      <%= render  "shared/navbar" %> 
         <%= yield %>   
      </div>   
   </body> 

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/destroy.html.erb
<h1>Movies#destroy</h1>
<p>Find me in app/views/movies/destroy.html.erb</p>

app/views/movies/edit.html.erb
<br><br><br><br>
 <h1>Apload Movie</h1> 
<%= form_for @movies, html: { multipart: true } do |f| %>   
    <%= f.label :title %>   
    <%= f.text_field :title %> 
    <br><br>
     <%= f.label :category %>   
    <%= f.text_field :category %>
    <br><br>
    <%= f.label :year %>   
    <%= f.text_field :year %>
    <br><br>
    <%= f.label :price %>   
    <%= f.text_field :price %>  
    <br><br>   
    <%= f.label :attachment %>   
    <%= f.file_field :attachment %>   
    <br>   
    <%= f.submit "update movie",class: "btn btn-primary" %>   
 <% end %>   

app/views/movies/home.html.erb
<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <br><br> <br><br>
    <div class="container">
      <h1 class="display-3">Jorah, Entertainment!</h1>
      <p><strong>Jorah Entertainment group company</strong>
is an online movie store company that located in Kigali Rwanda. We store all categories of movies (Rwandan, Western and Indian movies as well). In jorah, we also sell all that kinds of movies. Our website is trustworthy by that it is difficult to be attached by external intruders. We highly appreciates our partners especially our customers. For more about our services and product you can visit our website.</p>
     
      <%= link_to  "VISIT OUR MOVIESTORE", root_path %> 
       <br><br>
    <p>WELCOME IN JORAH ENTERNAINMENT GROUP COMPANY!!!!!!</p>
    </div>
  
</main>
<footer class="pt-4 my-md-5 pt-md-5 border-top bg-dark">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
        <small class="d-block mb-3 text-muted">&copy; 2017-2019</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Cool stuff</a></li>
          <li><a class="text-muted" href="#">Random feature</a></li>
          <li><a class="text-muted" href="#">Team feature</a></li>
          <li><a class="text-muted" href="#">Stuff for developers</a></li>
          <li><a class="text-muted" href="#">Another one</a></li>
         
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Resource</a></li>
          <li><a class="text-muted" href="#">Resource names</a></li>
          <li><a class="text-muted" href="#">other resource</a></li>
          <li><a class="text-muted" href="#"> Related resources</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Team</a></li>
          <li><a class="text-muted" href="#">Locations</a></li>
          <li><a class="text-muted" href="#">Privacy</a></li>
          <li><a class="text-muted" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>

app/views/movies/index.html.erb
<style>
img{
    width:300px;
    height:300px;
}

</style>


<br><br>
   

<div class="album py-5 bg-light">
        <div class="container">
        <div class="row">
 <% @movies.each do |m| %> 
          
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img src="<%= m.attachment %>" class="card-img-top"  alt="Card image cap">
                <div class="card-body">
                  <p class="card-text"><b>Title:</b><%= m.title %><br>
                  <b>category:</b><%= m.category %><br>
                  <b>Year:</b><%= m.year %><br>
                  <b>price:</b><%= m.price %></p>
                  
                  <b><u><%= link_to "Watch movie", m.attachment_url %></b></u>
                  <b><u><%= link_to "Delete",  m, method: :delete, confirm: "Are you sure you want to delete #{m.attachment}?" %>
                  </b></u>
                 
                  </div>
                </div>
              </div>
              <% end %> 
            </div>
            <footer class="pt-4 my-md-5 pt-md-5 border-top bg-dark">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
        <small class="d-block mb-3 text-muted">&copy; 2017-2019</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Cool stuff</a></li>
          <li><a class="text-muted" href="#">Random feature</a></li>
          <li><a class="text-muted" href="#">Team feature</a></li>
          <li><a class="text-muted" href="#">Stuff for developers</a></li>
          <li><a class="text-muted" href="#">Another one</a></li>
         
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Resource</a></li>
          <li><a class="text-muted" href="#">Resource names</a></li>
          <li><a class="text-muted" href="#">other resource</a></li>
          <li><a class="text-muted" href="#"> Related resources</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Team</a></li>
          <li><a class="text-muted" href="#">Locations</a></li>
          <li><a class="text-muted" href="#">Privacy</a></li>
          <li><a class="text-muted" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>


            

app/views/movies/new.html.erb
<br><br><br><br>
 <h1>Apload Movie</h1> 
<%= form_for @movies, html: { multipart: true } do |f| %>   
    <%= f.label :title %>   
    <%= f.text_field :title %> 
    <br><br>
     <%= f.label :category %>   
    <%= f.text_field :category %>
    <br><br>
    <%= f.label :year %>   
    <%= f.text_field :year %>
    <br><br>
    <%= f.label :price %>   
    <%= f.text_field :price %>  
    <br><br>   
    <%= f.label :attachment %>   
    <%= f.file_field :attachment %>   
    <br>   
    <%= f.submit "Save",class: "btn btn-primary" %>   
 <% end %>   
 <%= link_to  "back to home", root_path %>
<footer class="pt-4 my-md-5 pt-md-5 border-top bg-dark">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
        <small class="d-block mb-3 text-muted">&copy; 2017-2019</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Cool stuff</a></li>
          <li><a class="text-muted" href="#">Random feature</a></li>
          <li><a class="text-muted" href="#">Team feature</a></li>
          <li><a class="text-muted" href="#">Stuff for developers</a></li>
          <li><a class="text-muted" href="#">Another one</a></li>
         
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Resource</a></li>
          <li><a class="text-muted" href="#">Resource names</a></li>
          <li><a class="text-muted" href="#">other resource</a></li>
          <li><a class="text-muted" href="#"> Related resources</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Team</a></li>
          <li><a class="text-muted" href="#">Locations</a></li>
          <li><a class="text-muted" href="#">Privacy</a></li>
          <li><a class="text-muted" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>

app/views/movies/pricing.html.erb
<br><br>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Pricing</h1>
  <p class="lead">This is how our pricing policy is looking like!!. we offer free watchings, selling professionals. No where you can get our discounts<br>.Enjoy our products and services<br><strong><h1>welcoment in jorah entertainement!!!!</h1></strong></p>
</div>

<div class="container">
  <div class="card-deck mb-3 text-center">
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Free Movies</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$0 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>more 100 Movies included</li>
          <li>Action</li>
          <li>Love</li>
          <li>Fight</li>
        </ul>
        
      </div>
    </div>
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Pro</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$15 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>more 1000 Top Movies included</li>
          <li>Action</li>
          <li>Love</li>
          <li>Fight</li>
        </ul>
       
      </div>
    </div>
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Enterprise</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$29 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>30 users included</li>
          <li>15 GB of storage</li>
          <li>Phone and email support</li>
          <li>Help center access</li>
        </ul>
       
      </div>
    </div>
  </div>

  <footer class="pt-4 my-md-5 pt-md-5 border-top bg-dark">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
        <small class="d-block mb-3 text-muted">&copy; 2017-2019</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Cool stuff</a></li>
          <li><a class="text-muted" href="#">Random feature</a></li>
          <li><a class="text-muted" href="#">Team feature</a></li>
          <li><a class="text-muted" href="#">Stuff for developers</a></li>
          <li><a class="text-muted" href="#">Another one</a></li>
         
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Resource</a></li>
          <li><a class="text-muted" href="#">Resource names</a></li>
          <li><a class="text-muted" href="#">other resource</a></li>
          <li><a class="text-muted" href="#"> Related resources</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Team</a></li>
          <li><a class="text-muted" href="#">Locations</a></li>
          <li><a class="text-muted" href="#">Privacy</a></li>
          <li><a class="text-muted" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>

app/views/shared/_navbar.html.erb
<style>
li{
 margin-right: 150px;
}
</style>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapsed-1">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
        <%= link_to  "home", home_path %><br><br>   
        </li>
        
        <li class="nav-item">
         <%=link_to "moviesStore",root_path%>
        </li>
        
         <li class="nav-item">
         <%=link_to "pricing",pricing_path%>
        </li>
         <li class="nav-item"> 
        <%= link_to  "Apload movie Here", new_path %>
        </li>
        
       
      </ul>
      <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
 